# Generated by Django 3.2.1 on 2021-06-11 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_rssfeed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(default='descripito!'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='title',
            field=models.TextField(default='titilio!'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('live_date', models.DateField(auto_now=True)),
                ('link', models.TextField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssfeed')),
            ],
        ),
    ]
