# Generated by Django 3.2.1 on 2021-06-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20210611_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='rssfeed',
            name='url',
        ),
    ]
