# Generated by Django 3.2.1 on 2021-06-30 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_rssfeed_daily_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
