# Generated by Django 3.2.1 on 2021-06-29 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_rename_link_rssitem_content_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='daily_items',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
