# Generated by Django 3.2.5 on 2022-05-24 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_alter_rssfeed_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeed',
            name='daily_items',
        ),
        migrations.RemoveField(
            model_name='rssfeed',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='rssitem',
            name='live',
        ),
        migrations.RemoveField(
            model_name='rssitem',
            name='live_date',
        ),
        migrations.CreateModel(
            name='ConsumableFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.PositiveIntegerField(default=0)),
                ('daily_items', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssfeed')),
            ],
        ),
    ]
