# Generated by Django 3.2.5 on 2022-05-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0011_rssitem_ordinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumablefeed',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='consumablefeed',
            name='date_modified',
        ),
    ]
