# Generated by Django 3.2.5 on 2022-05-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0012_auto_20220531_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeed',
            name='length',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
