# Generated by Django 3.2.5 on 2022-08-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0013_rssfeed_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rssitem',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
